spring:
  application:
    name: swift-auth

  datasource:
    url: jdbc:postgresql://172.30.1.39:30432/auth?allowPublicKeyRetrieval=true&useSSL=false
    username: swift_auth
    password: R0ot@K3s#2026
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: 172.30.1.39
      port: 30379
      password: R0ot@K3s#2026

jwt:
  secret: sw1ft-4uth-s3cur3-jwt-s3cr3t-k3y-2026!
  access-token-expiration: 3600      # 1시간 (초)
  refresh-token-expiration: 1209600  # 14일 (초)
