POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "test@ngyu.me",
  "password": "Test1234!",
  "name": "남규"
}


### 로그인
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "test@ngyu.me",
  "password": "Test1234!"
}

> {%
  client.global.set("accessToken", response.body.accessToken);
%}

### OAuth 클라이언트 등록
POST http://localhost:8080/api/clients/register
Content-Type: application/json

{
  "name": "My Project",
  "redirectUri": "https://myapp.ngyu.me/callback",
  "scopes": "read,write"
}

### 내 정보 조회
GET http://localhost:8080/api/users/me
Authorization: Bearer {{accessToken}}
